---
name: Build Edge for Windows
"on":
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-amd64:
    runs-on: windows-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build
        env:
          CARGO_BUILD_JOBS: 2
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Publish
        shell: pwsh
        run: |
          curl \
          --user ${{ gitea.repository_owner }}:${{ secrets.TOKEN }} \
          -X DELETE \
          https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-x86_64.exe
          curl  \
          --user ${{ gitea.repository_owner }}:${{ secrets.TOKEN }} \
          --upload-file target/x86_64-pc-windows-msvc/release/puppet.exe \
          https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-x86_64.exe
