---
name: Build Edge for Windows
"on":
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".gitea/workflows/build-edge-win.yaml"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Build
        run: |
          apt-get install rustup -y
          rustup default stable
          cargo install cross

      - name: Build
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Publish
        run: |
          curl  \
          --user ${{ gitea.repository_owner }}:${{ secrets.TOKEN }} \
          --upload-file target/x86_64-pc-windows-gnu/release/puppet.exe \
          https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-x86_64.exe
