---
name: Build Edge for Windows
"on":
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-gnu:
    runs-on: windows-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        env:
          MSYS2_LOCATION: C:\Users\Pot\msys2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-base

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Build
        shell: msys2 {0}
        env:
          CARGO_BUILD_JOBS: 2
          PKG_CONFIG_ALLOW_CROSS: 1
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Publish
        shell: pwsh
        run: |
          curl.exe `
            --user "${{ gitea.repository_owner }}:${{ secrets.TOKEN }}" `
            -X DELETE `
            https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-gnu-x86_64.exe

          curl.exe `
            --user "${{ gitea.repository_owner }}:${{ secrets.TOKEN }}" `
            --upload-file target/x86_64-pc-windows-gnu/release/puppet.exe `
            https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-gnu-x86_64.exe

  build-msvc:
    runs-on: windows-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows
        with:
          vcpkgDirectory: 'C:\Users\Pot\vcpkg'
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Build
        env:
          CARGO_BUILD_JOBS: 2
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Publish
        shell: pwsh
        run: |
          curl.exe `
            --user "${{ gitea.repository_owner }}:${{ secrets.TOKEN }}" `
            -X DELETE `
            https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-x86_64.exe

          curl.exe `
            --user "${{ gitea.repository_owner }}:${{ secrets.TOKEN }}" `
            --upload-file target/x86_64-pc-windows-msvc/release/puppet.exe `
            https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-x86_64.exe
