---
name: Build Edge for glibc
"on":
  push:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye

    steps:
      - name: Prepare Checkouts
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          apt install nodejs -y

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Build
        run: |
          apt-get install -y \
            libasound2-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev
          rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Publish
        run: |
          curl \
          --user ${{ gitea.repository_owner }}:${{ secrets.TOKEN }} \
          -X DELETE \
          https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-glibc-amd64
          curl  \
          --user ${{ gitea.repository_owner }}:${{ secrets.TOKEN }} \
          --upload-file target/x86_64-unknown-linux-gnu/release/puppet \
          https://code.dawn.org.in/api/packages/${{ gitea.repository_owner }}/generic/puppet/edge/puppet-glibc-amd64
