FROM ubuntu:22.04

RUN apt update
RUN apt install build-essential nodejs curl libssl-dev -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
RUN apt install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev -y

WORKDIR /root

VOLUME /output

CMD ["bash"]
