FROM ubuntu:22.04

RUN apt clean && apt update
RUN apt install git build-essential patchelf file libfuse2 wget curl -y
RUN apt curl --proto '=https' --tlsv1.2 -sSf https://rustup.rs | sh -s -- -y
RUN DEBIAN_FRONTEND=noninteractive TZ=UTC apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav -y

RUN groupadd fuse
RUN usermod -a -G fuse root

WORKDIR /root

VOLUME /output

CMD ["bash"]
